### ISSUE TITLE
PH2 error

### ISSUE THREAD

**Issue by cpy0029** [wurenkai/UltraLight-VM-UNet#20]
Reading PH2
['/home/chen/datasets/PH2/images/IMD226.png', '/home/chen/datasets/PH2/images/IMD156.png', '/home/chen/datasets/PH2/images/IMD384.png', '/home/chen/datasets/PH2/images/IMD048.png', '/home/chen/datasets/PH2/images/IMD133.png', '/home/chen/datasets/PH2/images/IMD436.png', '/home/chen/datasets/PH2/images/IMD360.png', '/home/chen/datasets/PH2/images/IMD390.png', '/home/chen/datasets/PH2/images/IMD331.png', '/home/chen/datasets/PH2/images/IMD144.png', '/home/chen/datasets/PH2/images/IMD063.png', '/home/chen/datasets/PH2/images/IMD423.png', '/home/chen/datasets/PH2/images/IMD152.png', '/home/chen/datasets/PH2/images/IMD365.png', '/home/chen/datasets/PH2/images/IMD389.png', '/home/chen/datasets/PH2/images/IMD356.png', '/home/chen/datasets/PH2/images/IMD041.png', '/home/chen/datasets/PH2/images/IMD198.png', '/home/chen/datasets/PH2/images/IMD427.png', '/home/chen/datasets/PH2/images/IMD418.png', '/home/chen/datasets/PH2/images/IMD150.png', '/home/chen/datasets/PH2/images/IMD058.png', '/home/chen/datasets/PH2/images/IMD061.png', '/home/chen/datasets/PH2/images/IMD020.png', '/home/chen/datasets/PH2/images/IMD008.png', '/home/chen/datasets/PH2/images/IMD371.png', '/home/chen/datasets/PH2/images/IMD169.png', '/home/chen/datasets/PH2/images/IMD240.png', '/home/chen/datasets/PH2/images/IMD364.png', '/home/chen/datasets/PH2/images/IMD419.png', '/home/chen/datasets/PH2/images/IMD376.png', '/home/chen/datasets/PH2/images/IMD426.png', '/home/chen/datasets/PH2/images/IMD021.png', '/home/chen/datasets/PH2/images/IMD368.png', '/home/chen/datasets/PH2/images/IMD394.png', '/home/chen/datasets/PH2/images/IMD092.png', '/home/chen/datasets/PH2/images/IMD383.png', '/home/chen/datasets/PH2/images/IMD080.png', '/home/chen/datasets/PH2/images/IMD175.png', '/home/chen/datasets/PH2/images/IMD049.png', '/home/chen/datasets/PH2/images/IMD380.png', '/home/chen/datasets/PH2/images/IMD176.png', '/home/chen/datasets/PH2/images/IMD280.png', '/home/chen/datasets/PH2/images/IMD339.png', '/home/chen/datasets/PH2/images/IMD118.png', '/home/chen/datasets/PH2/images/IMD038.png', '/home/chen/datasets/PH2/images/IMD090.png', '/home/chen/datasets/PH2/images/IMD064.png', '/home/chen/datasets/PH2/images/IMD393.png', '/home/chen/datasets/PH2/images/IMD101.png', '/home/chen/datasets/PH2/images/IMD349.png', '/home/chen/datasets/PH2/images/IMD036.png', '/home/chen/datasets/PH2/images/IMD146.png', '/home/chen/datasets/PH2/images/IMD243.png', '/home/chen/datasets/PH2/images/IMD088.png', '/home/chen/datasets/PH2/images/IMD132.png', '/home/chen/datasets/PH2/images/IMD017.png', '/home/chen/datasets/PH2/images/IMD002.png', '/home/chen/datasets/PH2/images/IMD284.png', '/home/chen/datasets/PH2/images/IMD078.png', '/home/chen/datasets/PH2/images/IMD405.png', '/home/chen/datasets/PH2/images/IMD432.png', '/home/chen/datasets/PH2/images/IMD033.png', '/home/chen/datasets/PH2/images/IMD153.png', '/home/chen/datasets/PH2/images/IMD434.png', '/home/chen/datasets/PH2/images/IMD173.png', '/home/chen/datasets/PH2/images/IMD397.png', '/home/chen/datasets/PH2/images/IMD406.png', '/home/chen/datasets/PH2/images/IMD006.png', '/home/chen/datasets/PH2/images/IMD196.png', '/home/chen/datasets/PH2/images/IMD395.png', '/home/chen/datasets/PH2/images/IMD367.png', '/home/chen/datasets/PH2/images/IMD208.png', '/home/chen/datasets/PH2/images/IMD022.png', '/home/chen/datasets/PH2/images/IMD076.png', '/home/chen/datasets/PH2/images/IMD142.png', '/home/chen/datasets/PH2/images/IMD207.png', '/home/chen/datasets/PH2/images/IMD168.png', '/home/chen/datasets/PH2/images/IMD139.png', '/home/chen/datasets/PH2/images/IMD149.png', '/home/chen/datasets/PH2/images/IMD043.png', '/home/chen/datasets/PH2/images/IMD120.png', '/home/chen/datasets/PH2/images/IMD031.png', '/home/chen/datasets/PH2/images/IMD112.png', '/home/chen/datasets/PH2/images/IMD027.png', '/home/chen/datasets/PH2/images/IMD424.png', '/home/chen/datasets/PH2/images/IMD016.png', '/home/chen/datasets/PH2/images/IMD378.png', '/home/chen/datasets/PH2/images/IMD050.png', '/home/chen/datasets/PH2/images/IMD211.png', '/home/chen/datasets/PH2/images/IMD431.png', '/home/chen/datasets/PH2/images/IMD381.png', '/home/chen/datasets/PH2/images/IMD435.png', '/home/chen/datasets/PH2/images/IMD013.png', '/home/chen/datasets/PH2/images/IMD065.png', '/home/chen/datasets/PH2/images/IMD421.png', '/home/chen/datasets/PH2/images/IMD404.png', '/home/chen/datasets/PH2/images/IMD413.png', '/home/chen/datasets/PH2/images/IMD166.png', '/home/chen/datasets/PH2/images/IMD210.png', '/home/chen/datasets/PH2/images/IMD385.png', '/home/chen/datasets/PH2/images/IMD398.png', '/home/chen/datasets/PH2/images/IMD433.png', '/home/chen/datasets/PH2/images/IMD203.png', '/home/chen/datasets/PH2/images/IMD375.png', '/home/chen/datasets/PH2/images/IMD160.png', '/home/chen/datasets/PH2/images/IMD037.png', '/home/chen/datasets/PH2/images/IMD370.png', '/home/chen/datasets/PH2/images/IMD170.png', '/home/chen/datasets/PH2/images/IMD057.png', '/home/chen/datasets/PH2/images/IMD177.png', '/home/chen/datasets/PH2/images/IMD171.png', '/home/chen/datasets/PH2/images/IMD347.png', '/home/chen/datasets/PH2/images/IMD400.png', '/home/chen/datasets/PH2/images/IMD040.png', '/home/chen/datasets/PH2/images/IMD030.png', '/home/chen/datasets/PH2/images/IMD045.png', '/home/chen/datasets/PH2/images/IMD155.png', '/home/chen/datasets/PH2/images/IMD199.png', '/home/chen/datasets/PH2/images/IMD409.png', '/home/chen/datasets/PH2/images/IMD014.png', '/home/chen/datasets/PH2/images/IMD015.png', '/home/chen/datasets/PH2/images/IMD108.png', '/home/chen/datasets/PH2/images/IMD197.png', '/home/chen/datasets/PH2/images/IMD304.png', '/home/chen/datasets/PH2/images/IMD430.png', '/home/chen/datasets/PH2/images/IMD004.png', '/home/chen/datasets/PH2/images/IMD143.png', '/home/chen/datasets/PH2/images/IMD107.png', '/home/chen/datasets/PH2/images/IMD137.png', '/home/chen/datasets/PH2/images/IMD135.png', '/home/chen/datasets/PH2/images/IMD023.png', '/home/chen/datasets/PH2/images/IMD411.png', '/home/chen/datasets/PH2/images/IMD410.png', '/home/chen/datasets/PH2/images/IMD140.png', '/home/chen/datasets/PH2/images/IMD306.png', '/home/chen/datasets/PH2/images/IMD164.png', '/home/chen/datasets/PH2/images/IMD279.png', '/home/chen/datasets/PH2/images/IMD206.png', '/home/chen/datasets/PH2/images/IMD312.png', '/home/chen/datasets/PH2/images/IMD025.png', '/home/chen/datasets/PH2/images/IMD154.png', '/home/chen/datasets/PH2/images/IMD042.png', '/home/chen/datasets/PH2/images/IMD200.png', '/home/chen/datasets/PH2/images/IMD047.png', '/home/chen/datasets/PH2/images/IMD285.png', '/home/chen/datasets/PH2/images/IMD278.png', '/home/chen/datasets/PH2/images/IMD429.png', '/home/chen/datasets/PH2/images/IMD039.png', '/home/chen/datasets/PH2/images/IMD402.png', '/home/chen/datasets/PH2/images/IMD420.png', '/home/chen/datasets/PH2/images/IMD437.png', '/home/chen/datasets/PH2/images/IMD305.png', '/home/chen/datasets/PH2/images/IMD256.png', '/home/chen/datasets/PH2/images/IMD388.png', '/home/chen/datasets/PH2/images/IMD134.png', '/home/chen/datasets/PH2/images/IMD075.png', '/home/chen/datasets/PH2/images/IMD105.png', '/home/chen/datasets/PH2/images/IMD392.png', '/home/chen/datasets/PH2/images/IMD328.png', '/home/chen/datasets/PH2/images/IMD399.png', '/home/chen/datasets/PH2/images/IMD125.png', '/home/chen/datasets/PH2/images/IMD219.png', '/home/chen/datasets/PH2/images/IMD348.png', '/home/chen/datasets/PH2/images/IMD024.png', '/home/chen/datasets/PH2/images/IMD044.png', '/home/chen/datasets/PH2/images/IMD003.png', '/home/chen/datasets/PH2/images/IMD010.png', '/home/chen/datasets/PH2/images/IMD425.png', '/home/chen/datasets/PH2/images/IMD396.png', '/home/chen/datasets/PH2/images/IMD018.png', '/home/chen/datasets/PH2/images/IMD204.png', '/home/chen/datasets/PH2/images/IMD085.png', '/home/chen/datasets/PH2/images/IMD369.png', '/home/chen/datasets/PH2/images/IMD091.png', '/home/chen/datasets/PH2/images/IMD103.png', '/home/chen/datasets/PH2/images/IMD386.png', '/home/chen/datasets/PH2/images/IMD251.png', '/home/chen/datasets/PH2/images/IMD161.png', '/home/chen/datasets/PH2/images/IMD379.png', '/home/chen/datasets/PH2/images/IMD182.png', '/home/chen/datasets/PH2/images/IMD254.png', '/home/chen/datasets/PH2/images/IMD138.png', '/home/chen/datasets/PH2/images/IMD242.png', '/home/chen/datasets/PH2/images/IMD417.png', '/home/chen/datasets/PH2/images/IMD159.png', '/home/chen/datasets/PH2/images/IMD032.png', '/home/chen/datasets/PH2/images/IMD374.png', '/home/chen/datasets/PH2/images/IMD157.png', '/home/chen/datasets/PH2/images/IMD382.png', '/home/chen/datasets/PH2/images/IMD009.png', '/home/chen/datasets/PH2/images/IMD147.png', '/home/chen/datasets/PH2/images/IMD019.png', '/home/chen/datasets/PH2/images/IMD162.png', '/home/chen/datasets/PH2/images/IMD407.png', '/home/chen/datasets/PH2/images/IMD126.png', '/home/chen/datasets/PH2/images/IMD403.png', '/home/chen/datasets/PH2/images/IMD372.png', '/home/chen/datasets/PH2/images/IMD035.png', '/home/chen/datasets/PH2/images/IMD408.png']
1
Prepare_PH2.py:40: DeprecationWarning:     `imread` is deprecated!
    `imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
    Use ``imageio.imread`` instead.
  img = sc.imread(Tr_list[idx])
Prepare_PH2.py:41: DeprecationWarning:     `imresize` is deprecated!
    `imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.3.0.
    Use Pillow instead: ``numpy.array(Image.fromarray(arr).resize())``.
  img = np.double(sc.imresize(img, [height, width, channels], interp='bilinear', mode = 'RGB'))
Prepare_PH2.py:48: DeprecationWarning:     `imread` is deprecated!
    `imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
    Use ``imageio.imread`` instead.
  img2 = sc.imread(add)
Traceback (most recent call last):
  File "Prepare_PH2.py", line 48, in <module>
    img2 = sc.imread(add)
  File "/home/chen/anaconda3/envs/tool/lib/python3.7/site-packages/numpy/lib/utils.py", line 100, in newfunc
    return func(*args, **kwds)
  File "/home/chen/anaconda3/envs/tool/lib/python3.7/site-packages/scipy/misc/pilutil.py", line 164, in imread
    im = Image.open(name)
  File "/home/chen/anaconda3/envs/tool/lib/python3.7/site-packages/PIL/Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/chen/datasets/PH2/masks/mages/IMD226.png'

Here is the organizational structure of the images in my PH2/masks/ folder.
/home/chen/datasets/PH2/masks/
                                      IMD002_lesion.png
                                      IMD003_lesion.png
                                      IMD004_lesion.png
                                      .............

**Comment by wurenkai** [comment]
Hi, the file name of your masks is IMDxxx_lesion.png, which is not the same as the original image naming, so that line should be changed:
![image](https://github.com/wurenkai/UltraLight-VM-UNet/assets/124028634/e9cb4455-f94f-469f-af0d-76d6df2394bc)
```
add = (a+ 'masks/' + b +'_lesion.png')   
```
