### ISSUE TITLE
关于isic2017shujuji

### ISSUE THREAD

**Issue by lijincan11** [wurenkai/UltraLight-VM-UNet#3]
您好作者，您的研究非常的棒，但是我在复现的过程中出现了一点问题，训练完isic2017数据集后，进行测试的时候出现了如下的问题
../aten/src/ATen/native/cuda/Loss.cu:92: operator(): block: [71,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:92: operator(): block: [71,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:92: operator(): block: [71,0,0], thread: [29,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:92: operator(): block: [71,0,0], thread: [30,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:92: operator(): block: [71,0,0], thread: [31,0,0] Assertion `input_val >= zero && input_val <= one` failed.
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
 17%|██████████████████████████████████▋                                                                                                                                                                           | 101/600 [00:08<00:42, 11.78it/s]
Traceback (most recent call last):
  File "UltraLight-VM-UNet_17/train.py", line 171, in <module>
    main(config)
  File "UltraLight-VM-UNet_17/train.py", line 156, in main
    loss = test_one_epoch(
  File "/home/ljc/UltraLight-VM-UNet_17/engine.py", line 122, in test_one_epoch
    out = model(img)
  File "/home/xjl/anaconda3/envs/ulvm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xjl/anaconda3/envs/ulvm/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/xjl/anaconda3/envs/ulvm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ljc/UltraLight-VM-UNet_17/models/UltraLight_VM_UNet.py", line 210, in forward
    out = F.gelu(F.max_pool2d(self.ebn1(self.encoder1(x)),2,2))
  File "/home/xjl/anaconda3/envs/ulvm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xjl/anaconda3/envs/ulvm/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/xjl/anaconda3/envs/ulvm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xjl/anaconda3/envs/ulvm/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/xjl/anaconda3/envs/ulvm/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

**Comment by wurenkai** [comment]
Hi! Try restarting your environment and check if the output goes through a sigmoid activation function (return torch.sigmoid(out0)).

**Comment by heitorrapela** [comment]
Hello, thanks for the work. I am having the same error, I printed the output, and is giving nan

![image](https://github.com/wurenkai/UltraLight-VM-UNet/assets/14017613/720713a7-e5e7-45cd-afb9-54cd5535161b)

**Comment by heitorrapela** [comment]
I think that maybe the problem is in the Prepare_ISIC2017.py, we have to change it for the actual dataset provided on the README.md

**Comment by heitorrapela** [comment]
I fixed that installing the correct versions of the libraries for the preprocessing, then the data was okay to train, if someone have the same issue, here is the other thread about it: [Issue 4](https://github.com/wurenkai/UltraLight-VM-UNet/issues/4)

**Comment by wurenkai** [comment]
Yes, thank you. Whether the data is loaded correctly is also a key issue.

**Comment by ruti0823** [comment]
@lijincan11 Hello, I also encountered the same problem, how did you solve it?

**Comment by 730432ch** [comment]
作者你好我在数据预处理的时候没有出现您说的序号但是我是按照您的代码和环境配置进行预处理的然后程序出现nan的情况您可以帮我解答一下吗很急
