### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JackieWuuuuuu** [wurenkai/UltraLight-VM-UNet#57]
Traceback (most recent call last):
  File "train.py", line 189, in <module>
    main(config)
  File "train.py", line 132, in main
    train_one_epoch(
  File "/root/UltraLight-VM-UNet-main/engine.py", line 40, in train_one_epoch
    loss.backward()
  File "/root/miniconda3/envs/vmunet/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/root/miniconda3/envs/vmunet/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
用服务器跑，到Training的步骤就弹出这个报错，解决很久都无法解决，请问应该如何解决？

**Comment by wurenkai** [comment]
Hi, you may be able to get an answer to this question from [issue 6](https://github.com/wurenkai/UltraLight-VM-UNet/issues/6), or from [issue 4](https://github.com/wurenkai/H-vmunet/issues/4) of our other project.

**Comment by JackieWuuuuuu** [comment]
![屏幕截图 2024-09-08 163406](https://github.com/user-attachments/assets/a348ba86-70e1-4c22-8004-e4f56a706121)
请问数据集这样放置是否正确？分别只有images和masks的。
我的Prepare_ISIC2017.py是这样
![屏幕截图 2024-09-08 164441](https://github.com/user-attachments/assets/0b729492-d597-4cd6-a540-1163bf5e3780)
config_setting.py是这样
![屏幕截图 2024-09-08 164550](https://github.com/user-attachments/assets/1ef9535f-5f27-45ca-89b0-dc9b5aa99478)
运行Prepare_ISIC2017.py会得到这样的结果
![屏幕截图 2024-09-08 164636](https://github.com/user-attachments/assets/ef3eb8b8-41af-4231-ae92-d74b533a2962)
我认为是路径问题？您能帮我看看是什么问题吗？如果可以，十分感激！！

**Comment by wurenkai** [comment]
You are right, running Prepare_ISIC2017.py shows “[]” indicating that the image was not read correctly. You should make sure that the code Print(Tr_list) reads out the image naming. I see no problem with your current code, note that Prepare_ISIC2017.py is placed at the “/data” file directory level. Also, the image suffix inside images is jpg and inside masks the image is png, which is the suffix specified by the code so far.

In addition, we have provided code to prepare your own dataset, so you can take your own dataset (or substitute it for the ISIC2017 dataset), place it in the corresponding directory, and modify the number of training, validation, and test sets to run it. This will not have path problems.

**Comment by JackieWuuuuuu** [comment]
作者您好，我想问问应该如何对自己特定的数据集进行测试呢
![image](https://github.com/user-attachments/assets/cb0e0e78-360c-4f75-ab8b-6baa04626e60)
是只需要修改一下loader的中的路径就可以了吗（不用.npy文件测试，用自己的数据集测试）
![image](https://github.com/user-attachments/assets/d32d7cfa-9acb-4b33-8647-64f09a7d4a79)
在这里写入.pth的路径？如果您能帮助到我，十分感谢！

**Comment by ytuv** [comment]
> 十分感谢指导！已成功跑通，感谢！

你好，请问您在跑通代码后是否与论文的结果一致？我想以该论文为基准来改进，想问一下您的结果。十分感谢

**Comment by LiFeng-L** [comment]
![Image](https://github.com/user-attachments/assets/d6c8b2ca-8b6c-4c05-84dd-b37641e86c9f)请问我这样放哪里有问题呢，运行Prepare_ISIC2017.py会得到这样的结果

![Image](https://github.com/user-attachments/assets/af11e371-be6f-4fae-af46-1b0c9bc3a89e)您能也帮我看看是什么问题吗？如果可以，十分感激！
